spec:
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: "0.2"
            limits:
              cpu: "1.0"
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"tomcat":{"max-threads":1}}}'
            - name: JAVA_APP_JAR
              value: ${project.artifactId}-${project.version}.jar