
camel:
  springboot:
    name: fuse-rest-rh
    main-run-controller: true

server:
  address: 0.0.0.0
  port: 8090 #! ver restConfiguration
management:
  address: 0.0.0.0
  port: 8091

endpoints:
  enabled: false
  health:
    enabled: true

redhat:
  client-url: ${CLIENT_URL}